"""adjust_cascade

Revision ID: 2cccb7d7262c
Revises: b5ba826fe9fd
Create Date: 2026-07-18 18:38:55.254575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cccb7d7262c'
down_revision: Union[str, Sequence[str], None] = 'b5ba826fe9fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('costs_category_id_fkey'), 'costs', type_='foreignkey')
    op.drop_constraint(op.f('costs_description_id_fkey'), 'costs', type_='foreignkey')
    op.create_foreign_key(None, 'costs', 'categories_cost', ['category_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'costs', 'descriptions_cost', ['description_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('descriptions_cost_category_id_fkey'), 'descriptions_cost', type_='foreignkey')
    op.create_foreign_key(None, 'descriptions_cost', 'categories_cost', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'descriptions_cost', type_='foreignkey')
    op.create_foreign_key(op.f('descriptions_cost_category_id_fkey'), 'descriptions_cost', 'categories_cost', ['category_id'], ['id'])
    op.drop_constraint(None, 'costs', type_='foreignkey')
    op.drop_constraint(None, 'costs', type_='foreignkey')
    op.create_foreign_key(op.f('costs_description_id_fkey'), 'costs', 'descriptions_cost', ['description_id'], ['id'])
    op.create_foreign_key(op.f('costs_category_id_fkey'), 'costs', 'categories_cost', ['category_id'], ['id'])
    # ### end Alembic commands ###
