"""initial_migration

Revision ID: 51e216a5e0ed
Revises: 
Create Date: 2026-07-15 16:11:36.684733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51e216a5e0ed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories_cost',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token_blocklist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_blocklist_id'), 'token_blocklist', ['id'], unique=False)
    op.create_index(op.f('ix_token_blocklist_jti'), 'token_blocklist', ['jti'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('descriptions_cost',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories_cost.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('costs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cost_date', sa.DateTime(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('description_id', sa.UUID(), nullable=False),
    sa.Column('euro_amount', sa.Float(), nullable=False),
    sa.Column('amount_no_btw', sa.Float(), nullable=True),
    sa.Column('amount_btw', sa.Float(), nullable=True),
    sa.Column('btw_percent', sa.Float(), nullable=True),
    sa.Column('is_credit', sa.Boolean(), nullable=False),
    sa.Column('cost_note', sa.String(), nullable=True),
    sa.Column('supplier', sa.String(), nullable=True),
    sa.Column('invoice_nmb', sa.String(), nullable=True),
    sa.Column('ai_summary', sa.String(), nullable=True),
    sa.Column('year_reference', sa.Integer(), nullable=True),
    sa.Column('quarter_reference', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories_cost.id'], ),
    sa.ForeignKeyConstraint(['description_id'], ['descriptions_cost.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('costs')
    op.drop_table('descriptions_cost')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_token_blocklist_jti'), table_name='token_blocklist')
    op.drop_index(op.f('ix_token_blocklist_id'), table_name='token_blocklist')
    op.drop_table('token_blocklist')
    op.drop_table('categories_cost')
    # ### end Alembic commands ###
