"""add_crm_and_entries_tables

Revision ID: af6f7d0eb306
Revises: 51e216a5e0ed
Create Date: 2026-07-15 20:08:20.268412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af6f7d0eb306'
down_revision: Union[str, Sequence[str], None] = '51e216a5e0ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('postcode', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('nation', sa.String(length=100), nullable=True),
    sa.Column('telephone', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('btw', sa.String(length=25), nullable=True),
    sa.Column('kvk', sa.String(length=25), nullable=True),
    sa.Column('iban', sa.String(length=34), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('postcode', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('nation', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('btw', sa.String(length=25), nullable=True),
    sa.Column('kvk', sa.String(length=25), nullable=True),
    sa.Column('bankaccountname', sa.String(length=80), nullable=True),
    sa.Column('iban', sa.String(length=34), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('postcode', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('nation', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('btw', sa.String(length=25), nullable=True),
    sa.Column('kvk', sa.String(length=25), nullable=True),
    sa.Column('bankaccountname', sa.String(length=80), nullable=True),
    sa.Column('iban', sa.String(length=34), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loading_addresses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('postcode', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('nation', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('overdue_date', sa.Date(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('loading_address', sa.UUID(), nullable=True),
    sa.Column('quotation_reference', sa.String(length=11), nullable=True),
    sa.Column('invoice_reference', sa.String(length=11), nullable=True),
    sa.Column('is_invoice', sa.Boolean(), nullable=True),
    sa.Column('is_commission', sa.Boolean(), nullable=True),
    sa.Column('is_quotation', sa.Boolean(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('pallets_quantity', sa.Integer(), nullable=True),
    sa.Column('pallets_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pallets_total_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pallets_notes', sa.String(length=500), nullable=True),
    sa.Column('transport_gross', sa.Integer(), nullable=True),
    sa.Column('transport_bereken', sa.Integer(), nullable=True),
    sa.Column('transport_price_for_ton', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('transport_diesel_toeslag', sa.Integer(), nullable=True),
    sa.Column('transport_extra_stop', sa.Integer(), nullable=True),
    sa.Column('transport_extra_stop_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('transport_total_no_btw', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('transport_total_btw', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('temp_no_btw_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('no_btw_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('btw_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount', sa.Integer(), nullable=True),
    sa.Column('btw_total_discount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('final_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('loading_info', sa.String(length=300), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('year_reference', sa.Integer(), nullable=True),
    sa.Column('quarter_reference', sa.String(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['loading_address'], ['loading_addresses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_reference'),
    sa.UniqueConstraint('quotation_reference')
    )
    op.create_table('entry_products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entry_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unity', sa.Enum('M2', 'ML', 'BX', 'ST', 'FG', name='unitychoises'), nullable=False),
    sa.Column('unity_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entry_products')
    op.drop_table('entries')
    op.drop_table('loading_addresses')
    op.drop_table('suppliers')
    op.drop_table('customers')
    op.drop_table('company')
    # ### end Alembic commands ###
